name: main

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build
        run: |
          for dockerfile in tags/Dockerfile.*; do
            filename=$(basename -- "$dockerfile")
            tag="${filename##*.}"
            docker build --tag bneijt/archmatrix:$tag --file $dockerfile context
          done
      - name: scan
        uses: anchore/scan-action@v3
        with:
          image: bneijt/*
      - name: push
        run: echo NOP