name: main

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]
  schedule:
    - cron: "12 12 8 * *"

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - Aws
          - Pyenv39
          - Pyenv39A
          - Pyenv39Stripped
          - Pyenv310
          - Pyenv310A
          - Pyenv310Stripped
          - Tf12
          - Tf12Aws
    steps:
      - uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: WW
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          context: context
          file: tags/Dockerfile.${{ matrix.tag }}
          tags: |
            bneijt/archmatrix:${{ matrix.tag }}
            bneijt/archmatrix:${{ steps.current-time.outputs.formattedTime }}${{ matrix.tag }}
