name: main

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - Pyenv39
          - Pyenv39Stripped
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          context: context
          file: tags/Dockerfile.${{ matrix.tag }}
          tags: bneijt/archmatrix:${{ matrix.tag }}     
      # - name: scan
      #   uses: anchore/scan-action@v3
      #   with:
      #     image: bneijt/archmatrix:${{ matrix.tag }}
